### ISSUE TITLE
Sharing between apps

### ISSUE THREAD

**Issue by wlingke** [shazron/KeychainPlugin#19]
I am trying to use this plugin to share between apps. But it doesn't seem to work. I have the exact same service name and key in two different apps (aka two apps with different bundle ids) but cannot extract the information in second app that is set by first.

Is there something else I need to do to make this work?

**Comment by kirmandi** [comment]
would also like to achieve accessing the same data from two of my apps, any update/progress?

**Comment by Michael-Stanford** [comment]
Same here.

**Comment by DazChong** [comment]
I believe the `servicename` is already sandboxed within the app, hence same `servicename` of different apps definitely will not work; or else any app can just get your keychain value by just knowing the `servicename`.

Only native code possible now? (http://evgenii.com/blog/sharing-keychain-in-ios/)

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
