### ISSUE TITLE
No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

### ISSUE THREAD

**Issue by kiliankoller** [shazron/KeychainPlugin#21]
Hi,
we are using your KeychainPlugin together with
https://github.com/apache/cordova-ios.git#4.0.x
https://github.com/apache/cordova-plugins.git#master:wkwebview-engine
In this setup, we are seeing the compile error in the title.

When i comment out initWithWebView everything works
@see https://github.com/kiliankoller/KeychainPlugin

Is this ok?

Thanks, Kilian

**Comment by shazron** [comment]
Yes that is fine. initWithWebView goes away in cordova-ios 4.0, all plugin initialization should be in the pluginInitialize function. Since initWithWebView for the plugin does nothing, no migration needed.
