### ISSUE TITLE
Get values posted with native plugin sskeychain

### ISSUE THREAD

**Issue by nespapu** [shazron/KeychainPlugin#22]
We are having a tough time trying to shared info between two apps with keychain service.

We have two apps:

1.- CoreApp, which is native and use this plugin [SSKEYCHAIN](https://github.com/soffes/sskeychain) to set values:

    + (BOOL)setPassword:(NSString *)password forService:(NSString *)serviceName account:(NSString *)account; 

Where are setting for paramenter the following values:

    password = aaa
    serviceName = bbb
    account = ccc

2.- SatelliteApp, which is hybrid (cordova) and use this plugin [KeychainPlugin](https://github.com/shazron/KeychainPlugin) to get values:

    kc.getForKey(successCallback, failureCallback, 'ccc', 'bbb');

The failureCallback is triggered with the message:

    "Error retrieving vale for key ccc : (null)"

We have done some tests:

1.- We have do another native app that queries the keychain populated by CoreApp and it works good.

2.- we have do another hybrid app that set values in the keychain and the SatelliteApp queries it succesfully.

It seems like we are not setting the values in the same container that we are retreiving the values from the other app. But we do not know how to point all the apps to the same place.

Has anyone idea what could be happening? Any hint, test to do or advice would be highly appreciated.

Thanks very much.

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
