### ISSUE TITLE
Is there easy way to disable iCloud syncing?

### ISSUE THREAD

**Issue by rwillett** [shazron/KeychainPlugin#23]
Hi,

Thanks for the plugin. It seems to work well but we've just realised that the iCloud syncing creates a problem for us and we're trying to work out of there is a simple way to stop syncing for the keys for our app.

The reason we want to do this is as follows:

1. We are using the Apple IDFV value as a unique indentifier for our app. This identifier is used to pull data back from our servers and holds information specific to a user and their specific device.

2. When a user uninstalls our app AND it is the last of our apps (though we only have one), then the IDFV is removed and if the user reinstalls our app then a new IDFV is created.

3. Since the only mechanism we have for the user to get their data back is through the IDFV (or any other unique ID), their data is lost as a new IDFV is created and there is no way to get access to the old IDFV.

4. Ay other identifier we use faces the same problem that when the app is installed the identifier is lost. (AFAWK)

5. We use the keychain to store the IDFV so that it persists across app installations which we know works well as we've implemented this plugin :)

6. However if the user has two iDevices AND has iCloud syncing turned on, then the second (or subsequent iDevice will get the first IDFV. This means that the user will pick up the copy of the user data from the first device on their second device which is NOT what we want.

7. We know we can ask the user to create a unique name or id for themselves, such as using an e-mail address, but our user testing shows that users don't want to do this and simply want to 'use' their device without having to do extra work and we don't really blame them for this.

So the 64c questions is, how can we disable iCloud syncing for the keys we use in this plugin alone? We've looked at the code and are not Objective C programmers so we're struggling to understand what creates the synchronisation.

We understand that some keys are NOT synchronised across the iCloud so this should be doable...

At the official documentation Apple states:
"[...] the entire keychain is not synced. Some items are device-specific, such
as VPN identities, and shouldn’t leave the device. Only items with the attribute
kSecAttrSynchronizable are synced."

https://www.apple.com/euro/iphone/business/b/generic/docs/iOS_Security_Feb14.pdf

Any help or advice welcomed, 

Thanks,

Rob

**Comment by rwillett** [comment]
After looking at the source code we *think* that all we need to do is remove the attribute, kSecAttrSynchronizable and its associated value from the object arrays.

It would be good to know if thats all that is needed. 

Rob

**Comment by matuskopo** [comment]
Hi, I have same problem. But I understand Objective-C so I searched sources for kSecAttrSynchronizable key and found a solution. That key is defined in file SFHFKeychainUtils.m in 4 arrays. Just search for it. Each time it's used in array of keys. Always there is below same sized array of objects for that keys. Just change kCFBooleanTrue constant to kCFBooleanFalse in each objects array on same position as kSecAttrSynchronizable key's position is in keys array. Hope this helps. Bye

**Comment by rwillett** [comment]
Thanks,

Have worked this out now :) 

I've forked a version so I don;t keep having to do it.

best wishes

Rob
