### ISSUE TITLE
Support for TouchID authenticated entries?

### ISSUE THREAD

**Issue by nwocykra** [shazron/KeychainPlugin#27]
I was wondering if this plugin can be used in combination with Touch ID?

We need to have certain keychain entries accessible only with Touch ID authentication.

If not, is support for this in the pipeline?

**Comment by davidjb** [comment]
+1 I'm interested in this as well; essentially, I'm looking to do what a library like Valet does (https://github.com/square/Valet#protecting-secrets-with-touch-id-or-device-passcode) with the secure enclave.

**Comment by mlynch** [comment]
Hi, I've forked this plugin and created one with support for TouchID: https://github.com/driftyco/cordova-plugin-ios-keychain

Let me know if you try it and have any feedback!

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
