### ISSUE TITLE
Is it possible to use this plugin and iOS keychain to automatically login to Cordova app?

### ISSUE THREAD

**Issue by lumierephoto** [shazron/KeychainPlugin#28]
I'm looking for a possible solution to login to a Cordova iOS app automatically using the iOS keychain.

Is this possible? Can this plugin help?

I've tried looking at this KeychainPlugin, but his example only shows playing with getting, setting and deleting the keys for predefined values.

How can this plugin use the values in the keychain already? Is there a simple example of how this can be done? I can't find this info anywhere. At least not for a Cordova project.

Any help would be great!

**Comment by SimpleDeveloper49** [comment]
In the onDeviceReady event, get the keychain values, do your login logic, continue.

Is that what you are looking for? What do you mean by login automatically?

**Comment by tabrindle** [comment]
This kind of functionality already exists in another plugin that extends this one -https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
