### ISSUE TITLE
error when build cordova app

### ISSUE THREAD

**Issue by dongdh** [shazron/KeychainPlugin#31]
error: no visible @interface for
      'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVKeychain*)[super initWithWebView:(UIWebView*)theWebView];

Xcode version 7.2.1
cordova iOS 4.1.0

**Comment by shazron** [comment]
See https://github.com/shazron/KeychainPlugin/issues/20#issuecomment-179558927
