### ISSUE TITLE
Not able to read from keychain during background update in iOS 7

### ISSUE THREAD

**Issue by shazron** [shazron/KeychainPlugin#9]
From: http://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background?answertab=votes#tab-top

Lines: https://github.com/shazron/KeychainPlugin/blob/104bc0006018e0de40485f77ec4fb947cf6055a3/src/ios/SFHFKeychainUtils/SFHFKeychainUtils.m#L212-L213

Add the key "kSecAttrAccessible" with value "kSecAttrAccessibleAlways". 

Note this is insecure (the default is kSecAttrAccessibleWhenUnlocked). The best option is to use this method: http://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background?answertab=votes#comment28594533_10583042

**Comment by jacquesdev** [comment]
@mlynch - based on my previous comments in #20, I just wanted to check, do you think your fork addresses this particular issue. In other words to your knowledge does it include this keychain security setting? If yes, I will be switching over to your fork asap and can give you feedback after.

**Comment by mlynch** [comment]
I don't know, but looking through the library I'm using underneath, it does appear to incorporate some of those suggested changes from the SO post. It's sufficiently different that it's worth trying out.

**Comment by jacquesdev** [comment]
Thanks @mlynch. Happy to test it, I can't seem to log any issues though, is that something you can perhaps turn on on the fork?

 I do see an interesting thing when trying to run my ionic project with this plugin.

For some reason the path where it builds the files is different to where it is expecting it, as in the screenshot below.

![desctop screenshot](https://cloud.githubusercontent.com/assets/7842197/17348218/c860f76e-590c-11e6-8eae-13c152486c8a.png)

Is this something I am doing wrong on my side? To test it, i will just update the path for now.

**Comment by mlynch** [comment]
Done, we can continue the discussion over there, in the meantime I'll check on that one https://github.com/driftyco/cordova-plugin-ios-keychain/issues

**Comment by mlynch** [comment]
@jacquesdev try removing and adding it again, just fixed that issue.

*See you on the other repo...*

**Comment by shazron** [comment]
See updated README: https://github.com/shazron/KeychainPlugin/blob/master/README.md
